// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: ziggurat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InputRefs     map[string]string      `protobuf:"bytes,4,rep,name=input_refs,json=inputRefs,proto3" json:"input_refs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // name -> content hash
	Artifacts     []string               `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`                                                                                            // content hashes
	Params        map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Requires      []string               `protobuf:"bytes,7,rep,name=requires,proto3" json:"requires,omitempty"`
	Constraints   []string               `protobuf:"bytes,8,rep,name=constraints,proto3" json:"constraints,omitempty"`
	Priority      int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	TimeoutNs     int64                  `protobuf:"varint,10,opt,name=timeout_ns,json=timeoutNs,proto3" json:"timeout_ns,omitempty"` // nanoseconds, 0 = cluster default
	MaxRetries    int32                  `protobuf:"varint,11,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	MaxOutputSize int64                  `protobuf:"varint,12,opt,name=max_output_size,json=maxOutputSize,proto3" json:"max_output_size,omitempty"`
	Affinity      string                 `protobuf:"bytes,13,opt,name=affinity,proto3" json:"affinity,omitempty"`
	KeepWorkspace bool                   `protobuf:"varint,14,opt,name=keep_workspace,json=keepWorkspace,proto3" json:"keep_workspace,omitempty"`
	Image         string                 `protobuf:"bytes,15,opt,name=image,proto3" json:"image,omitempty"`
	Attempt       int32                  `protobuf:"varint,16,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Environment   *TaskEnvironment       `protobuf:"bytes,17,opt,name=environment,proto3" json:"environment,omitempty"` // persistent env config (optional)
	Resources     *TaskResources         `protobuf:"bytes,18,opt,name=resources,proto3" json:"resources,omitempty"`     // resource requests (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskRequest) Reset() {
	*x = DispatchTaskRequest{}
	mi := &file_ziggurat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskRequest) ProtoMessage() {}

func (x *DispatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskRequest.ProtoReflect.Descriptor instead.
func (*DispatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DispatchTaskRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DispatchTaskRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *DispatchTaskRequest) GetInputRefs() map[string]string {
	if x != nil {
		return x.InputRefs
	}
	return nil
}

func (x *DispatchTaskRequest) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *DispatchTaskRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *DispatchTaskRequest) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *DispatchTaskRequest) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *DispatchTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DispatchTaskRequest) GetTimeoutNs() int64 {
	if x != nil {
		return x.TimeoutNs
	}
	return 0
}

func (x *DispatchTaskRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *DispatchTaskRequest) GetMaxOutputSize() int64 {
	if x != nil {
		return x.MaxOutputSize
	}
	return 0
}

func (x *DispatchTaskRequest) GetAffinity() string {
	if x != nil {
		return x.Affinity
	}
	return ""
}

func (x *DispatchTaskRequest) GetKeepWorkspace() bool {
	if x != nil {
		return x.KeepWorkspace
	}
	return false
}

func (x *DispatchTaskRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DispatchTaskRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DispatchTaskRequest) GetEnvironment() *TaskEnvironment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *DispatchTaskRequest) GetResources() *TaskResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

// TaskResources specifies resource requests for scheduler admission.
type TaskResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        int64                  `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`                     // bytes, 0 = no requirement
	CpuCores      int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"` // logical cores, 0 = no requirement
	Gpus          int32                  `protobuf:"varint,3,opt,name=gpus,proto3" json:"gpus,omitempty"`                         // GPU devices, 0 = no requirement
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResources) Reset() {
	*x = TaskResources{}
	mi := &file_ziggurat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResources) ProtoMessage() {}

func (x *TaskResources) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResources.ProtoReflect.Descriptor instead.
func (*TaskResources) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResources) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *TaskResources) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *TaskResources) GetGpus() int32 {
	if x != nil {
		return x.Gpus
	}
	return 0
}

// TaskEnvironment configures a persistent, reusable environment for a task.
type TaskEnvironment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // explicit env name; empty = derive from fingerprint
	Setup         []string               `protobuf:"bytes,2,rep,name=setup,proto3" json:"setup,omitempty"`             // command to run when env needs (re)creation
	Fingerprint   []string               `protobuf:"bytes,3,rep,name=fingerprint,proto3" json:"fingerprint,omitempty"` // filenames whose content hash determines staleness
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEnvironment) Reset() {
	*x = TaskEnvironment{}
	mi := &file_ziggurat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnvironment) ProtoMessage() {}

func (x *TaskEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnvironment.ProtoReflect.Descriptor instead.
func (*TaskEnvironment) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{2}
}

func (x *TaskEnvironment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskEnvironment) GetSetup() []string {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *TaskEnvironment) GetFingerprint() []string {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

type DispatchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                             // set if accepted=false
	AssignedId    string                 `protobuf:"bytes,3,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"` // the task ID assigned by the receiving coordinator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskResponse) Reset() {
	*x = DispatchTaskResponse{}
	mi := &file_ziggurat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResponse) ProtoMessage() {}

func (x *DispatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResponse.ProtoReflect.Descriptor instead.
func (*DispatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DispatchTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DispatchTaskResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

type TaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultRequest) Reset() {
	*x = TaskResultRequest{}
	mi := &file_ziggurat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultRequest) ProtoMessage() {}

func (x *TaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultRequest.ProtoReflect.Descriptor instead.
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	OutputRef     string                 `protobuf:"bytes,6,opt,name=output_ref,json=outputRef,proto3" json:"output_ref,omitempty"`
	OutputBytes   int64                  `protobuf:"varint,7,opt,name=output_bytes,json=outputBytes,proto3" json:"output_bytes,omitempty"`
	WallTimeNs    int64                  `protobuf:"varint,8,opt,name=wall_time_ns,json=wallTimeNs,proto3" json:"wall_time_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultResponse) Reset() {
	*x = TaskResultResponse{}
	mi := &file_ziggurat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultResponse) ProtoMessage() {}

func (x *TaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultResponse.ProtoReflect.Descriptor instead.
func (*TaskResultResponse) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResultResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResultResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TaskResultResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *TaskResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResultResponse) GetOutputRef() string {
	if x != nil {
		return x.OutputRef
	}
	return ""
}

func (x *TaskResultResponse) GetOutputBytes() int64 {
	if x != nil {
		return x.OutputBytes
	}
	return 0
}

func (x *TaskResultResponse) GetWallTimeNs() int64 {
	if x != nil {
		return x.WallTimeNs
	}
	return 0
}

type PullShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // BLAKE3 content hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullShardRequest) Reset() {
	*x = PullShardRequest{}
	mi := &file_ziggurat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullShardRequest) ProtoMessage() {}

func (x *PullShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullShardRequest.ProtoReflect.Descriptor instead.
func (*PullShardRequest) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{6}
}

func (x *PullShardRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ShardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // chunk of object data (up to 256KB per message)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardData) Reset() {
	*x = ShardData{}
	mi := &file_ziggurat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardData) ProtoMessage() {}

func (x *ShardData) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardData.ProtoReflect.Descriptor instead.
func (*ShardData) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{7}
}

func (x *ShardData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushShardMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PushShardMsg_Header
	//	*PushShardMsg_Data
	Payload       isPushShardMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushShardMsg) Reset() {
	*x = PushShardMsg{}
	mi := &file_ziggurat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushShardMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushShardMsg) ProtoMessage() {}

func (x *PushShardMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushShardMsg.ProtoReflect.Descriptor instead.
func (*PushShardMsg) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{8}
}

func (x *PushShardMsg) GetPayload() isPushShardMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushShardMsg) GetHeader() *PushShardHeader {
	if x != nil {
		if x, ok := x.Payload.(*PushShardMsg_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *PushShardMsg) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PushShardMsg_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPushShardMsg_Payload interface {
	isPushShardMsg_Payload()
}

type PushShardMsg_Header struct {
	Header *PushShardHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type PushShardMsg_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // chunk of object data (up to 256KB per message)
}

func (*PushShardMsg_Header) isPushShardMsg_Payload() {}

func (*PushShardMsg_Data) isPushShardMsg_Payload() {}

type PushShardHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                 // expected total size
	ShardIndex    int32                  `protobuf:"varint,3,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`   // EC shard index (-1 or 0 = full blob, >0 = erasure shard)
	IsEcShard     bool                   `protobuf:"varint,4,opt,name=is_ec_shard,json=isEcShard,proto3" json:"is_ec_shard,omitempty"`    // true when this is an individual erasure-coded shard
	ErasureMeta   []byte                 `protobuf:"bytes,5,opt,name=erasure_meta,json=erasureMeta,proto3" json:"erasure_meta,omitempty"` // JSON-encoded ErasureParams (sent with EC shards for receiver metadata)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushShardHeader) Reset() {
	*x = PushShardHeader{}
	mi := &file_ziggurat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushShardHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushShardHeader) ProtoMessage() {}

func (x *PushShardHeader) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushShardHeader.ProtoReflect.Descriptor instead.
func (*PushShardHeader) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{9}
}

func (x *PushShardHeader) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PushShardHeader) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PushShardHeader) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

func (x *PushShardHeader) GetIsEcShard() bool {
	if x != nil {
		return x.IsEcShard
	}
	return false
}

func (x *PushShardHeader) GetErasureMeta() []byte {
	if x != nil {
		return x.ErasureMeta
	}
	return nil
}

type PushShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushShardResponse) Reset() {
	*x = PushShardResponse{}
	mi := &file_ziggurat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushShardResponse) ProtoMessage() {}

func (x *PushShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushShardResponse.ProtoReflect.Descriptor instead.
func (*PushShardResponse) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{10}
}

func (x *PushShardResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PushShardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PullECShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                // BLAKE3 content hash of the parent object
	ShardIndex    int32                  `protobuf:"varint,2,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"` // which shard to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullECShardRequest) Reset() {
	*x = PullECShardRequest{}
	mi := &file_ziggurat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullECShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullECShardRequest) ProtoMessage() {}

func (x *PullECShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullECShardRequest.ProtoReflect.Descriptor instead.
func (*PullECShardRequest) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{11}
}

func (x *PullECShardRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PullECShardRequest) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

type RetireReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // BLAKE3 content hash of the object to retire
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetireReplicaRequest) Reset() {
	*x = RetireReplicaRequest{}
	mi := &file_ziggurat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetireReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetireReplicaRequest) ProtoMessage() {}

func (x *RetireReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetireReplicaRequest.ProtoReflect.Descriptor instead.
func (*RetireReplicaRequest) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{12}
}

func (x *RetireReplicaRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type RetireReplicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetireReplicaResponse) Reset() {
	*x = RetireReplicaResponse{}
	mi := &file_ziggurat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetireReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetireReplicaResponse) ProtoMessage() {}

func (x *RetireReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetireReplicaResponse.ProtoReflect.Descriptor instead.
func (*RetireReplicaResponse) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{13}
}

func (x *RetireReplicaResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RetireReplicaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_ziggurat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{14}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_ziggurat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ziggurat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_ziggurat_proto_rawDescGZIP(), []int{15}
}

func (x *CancelTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CancelTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_ziggurat_proto protoreflect.FileDescriptor

const file_ziggurat_proto_rawDesc = "" +
	"\n" +
	"\x0eziggurat.proto\x12\bziggurat\"\x81\a\n" +
	"\x13DispatchTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x128\n" +
	"\x03env\x18\x03 \x03(\v2&.ziggurat.DispatchTaskRequest.EnvEntryR\x03env\x12K\n" +
	"\n" +
	"input_refs\x18\x04 \x03(\v2,.ziggurat.DispatchTaskRequest.InputRefsEntryR\tinputRefs\x12\x1c\n" +
	"\tartifacts\x18\x05 \x03(\tR\tartifacts\x12A\n" +
	"\x06params\x18\x06 \x03(\v2).ziggurat.DispatchTaskRequest.ParamsEntryR\x06params\x12\x1a\n" +
	"\brequires\x18\a \x03(\tR\brequires\x12 \n" +
	"\vconstraints\x18\b \x03(\tR\vconstraints\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"timeout_ns\x18\n" +
	" \x01(\x03R\ttimeoutNs\x12\x1f\n" +
	"\vmax_retries\x18\v \x01(\x05R\n" +
	"maxRetries\x12&\n" +
	"\x0fmax_output_size\x18\f \x01(\x03R\rmaxOutputSize\x12\x1a\n" +
	"\baffinity\x18\r \x01(\tR\baffinity\x12%\n" +
	"\x0ekeep_workspace\x18\x0e \x01(\bR\rkeepWorkspace\x12\x14\n" +
	"\x05image\x18\x0f \x01(\tR\x05image\x12\x18\n" +
	"\aattempt\x18\x10 \x01(\x05R\aattempt\x12;\n" +
	"\venvironment\x18\x11 \x01(\v2\x19.ziggurat.TaskEnvironmentR\venvironment\x125\n" +
	"\tresources\x18\x12 \x01(\v2\x17.ziggurat.TaskResourcesR\tresources\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eInputRefsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\rTaskResources\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\x03R\x06memory\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12\x12\n" +
	"\x04gpus\x18\x03 \x01(\x05R\x04gpus\"]\n" +
	"\x0fTaskEnvironment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05setup\x18\x02 \x03(\tR\x05setup\x12 \n" +
	"\vfingerprint\x18\x03 \x03(\tR\vfingerprint\"i\n" +
	"\x14DispatchTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vassigned_id\x18\x03 \x01(\tR\n" +
	"assignedId\",\n" +
	"\x11TaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xf4\x01\n" +
	"\x12TaskResultResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"output_ref\x18\x06 \x01(\tR\toutputRef\x12!\n" +
	"\foutput_bytes\x18\a \x01(\x03R\voutputBytes\x12 \n" +
	"\fwall_time_ns\x18\b \x01(\x03R\n" +
	"wallTimeNs\"&\n" +
	"\x10PullShardRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\x1f\n" +
	"\tShardData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"d\n" +
	"\fPushShardMsg\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x19.ziggurat.PushShardHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x9d\x01\n" +
	"\x0fPushShardHeader\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1f\n" +
	"\vshard_index\x18\x03 \x01(\x05R\n" +
	"shardIndex\x12\x1e\n" +
	"\vis_ec_shard\x18\x04 \x01(\bR\tisEcShard\x12!\n" +
	"\ferasure_meta\x18\x05 \x01(\fR\verasureMeta\"9\n" +
	"\x11PushShardResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\x12PullECShardRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1f\n" +
	"\vshard_index\x18\x02 \x01(\x05R\n" +
	"shardIndex\"*\n" +
	"\x14RetireReplicaRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"=\n" +
	"\x15RetireReplicaResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\":\n" +
	"\x12CancelTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x89\x04\n" +
	"\fZigguratNode\x12M\n" +
	"\fDispatchTask\x12\x1d.ziggurat.DispatchTaskRequest\x1a\x1e.ziggurat.DispatchTaskResponse\x12G\n" +
	"\n" +
	"TaskResult\x12\x1b.ziggurat.TaskResultRequest\x1a\x1c.ziggurat.TaskResultResponse\x12>\n" +
	"\tPullShard\x12\x1a.ziggurat.PullShardRequest\x1a\x13.ziggurat.ShardData0\x01\x12B\n" +
	"\tPushShard\x12\x16.ziggurat.PushShardMsg\x1a\x1b.ziggurat.PushShardResponse(\x01\x12B\n" +
	"\vPullECShard\x12\x1c.ziggurat.PullECShardRequest\x1a\x13.ziggurat.ShardData0\x01\x12P\n" +
	"\rRetireReplica\x12\x1e.ziggurat.RetireReplicaRequest\x1a\x1f.ziggurat.RetireReplicaResponse\x12G\n" +
	"\n" +
	"CancelTask\x12\x1b.ziggurat.CancelTaskRequest\x1a\x1c.ziggurat.CancelTaskResponseB6Z4github.com/syzygyhack/ziggurat/internal/transport/pbb\x06proto3"

var (
	file_ziggurat_proto_rawDescOnce sync.Once
	file_ziggurat_proto_rawDescData []byte
)

func file_ziggurat_proto_rawDescGZIP() []byte {
	file_ziggurat_proto_rawDescOnce.Do(func() {
		file_ziggurat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ziggurat_proto_rawDesc), len(file_ziggurat_proto_rawDesc)))
	})
	return file_ziggurat_proto_rawDescData
}

var file_ziggurat_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ziggurat_proto_goTypes = []any{
	(*DispatchTaskRequest)(nil),   // 0: ziggurat.DispatchTaskRequest
	(*TaskResources)(nil),         // 1: ziggurat.TaskResources
	(*TaskEnvironment)(nil),       // 2: ziggurat.TaskEnvironment
	(*DispatchTaskResponse)(nil),  // 3: ziggurat.DispatchTaskResponse
	(*TaskResultRequest)(nil),     // 4: ziggurat.TaskResultRequest
	(*TaskResultResponse)(nil),    // 5: ziggurat.TaskResultResponse
	(*PullShardRequest)(nil),      // 6: ziggurat.PullShardRequest
	(*ShardData)(nil),             // 7: ziggurat.ShardData
	(*PushShardMsg)(nil),          // 8: ziggurat.PushShardMsg
	(*PushShardHeader)(nil),       // 9: ziggurat.PushShardHeader
	(*PushShardResponse)(nil),     // 10: ziggurat.PushShardResponse
	(*PullECShardRequest)(nil),    // 11: ziggurat.PullECShardRequest
	(*RetireReplicaRequest)(nil),  // 12: ziggurat.RetireReplicaRequest
	(*RetireReplicaResponse)(nil), // 13: ziggurat.RetireReplicaResponse
	(*CancelTaskRequest)(nil),     // 14: ziggurat.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 15: ziggurat.CancelTaskResponse
	nil,                           // 16: ziggurat.DispatchTaskRequest.EnvEntry
	nil,                           // 17: ziggurat.DispatchTaskRequest.InputRefsEntry
	nil,                           // 18: ziggurat.DispatchTaskRequest.ParamsEntry
}
var file_ziggurat_proto_depIdxs = []int32{
	16, // 0: ziggurat.DispatchTaskRequest.env:type_name -> ziggurat.DispatchTaskRequest.EnvEntry
	17, // 1: ziggurat.DispatchTaskRequest.input_refs:type_name -> ziggurat.DispatchTaskRequest.InputRefsEntry
	18, // 2: ziggurat.DispatchTaskRequest.params:type_name -> ziggurat.DispatchTaskRequest.ParamsEntry
	2,  // 3: ziggurat.DispatchTaskRequest.environment:type_name -> ziggurat.TaskEnvironment
	1,  // 4: ziggurat.DispatchTaskRequest.resources:type_name -> ziggurat.TaskResources
	9,  // 5: ziggurat.PushShardMsg.header:type_name -> ziggurat.PushShardHeader
	0,  // 6: ziggurat.ZigguratNode.DispatchTask:input_type -> ziggurat.DispatchTaskRequest
	4,  // 7: ziggurat.ZigguratNode.TaskResult:input_type -> ziggurat.TaskResultRequest
	6,  // 8: ziggurat.ZigguratNode.PullShard:input_type -> ziggurat.PullShardRequest
	8,  // 9: ziggurat.ZigguratNode.PushShard:input_type -> ziggurat.PushShardMsg
	11, // 10: ziggurat.ZigguratNode.PullECShard:input_type -> ziggurat.PullECShardRequest
	12, // 11: ziggurat.ZigguratNode.RetireReplica:input_type -> ziggurat.RetireReplicaRequest
	14, // 12: ziggurat.ZigguratNode.CancelTask:input_type -> ziggurat.CancelTaskRequest
	3,  // 13: ziggurat.ZigguratNode.DispatchTask:output_type -> ziggurat.DispatchTaskResponse
	5,  // 14: ziggurat.ZigguratNode.TaskResult:output_type -> ziggurat.TaskResultResponse
	7,  // 15: ziggurat.ZigguratNode.PullShard:output_type -> ziggurat.ShardData
	10, // 16: ziggurat.ZigguratNode.PushShard:output_type -> ziggurat.PushShardResponse
	7,  // 17: ziggurat.ZigguratNode.PullECShard:output_type -> ziggurat.ShardData
	13, // 18: ziggurat.ZigguratNode.RetireReplica:output_type -> ziggurat.RetireReplicaResponse
	15, // 19: ziggurat.ZigguratNode.CancelTask:output_type -> ziggurat.CancelTaskResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ziggurat_proto_init() }
func file_ziggurat_proto_init() {
	if File_ziggurat_proto != nil {
		return
	}
	file_ziggurat_proto_msgTypes[8].OneofWrappers = []any{
		(*PushShardMsg_Header)(nil),
		(*PushShardMsg_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ziggurat_proto_rawDesc), len(file_ziggurat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ziggurat_proto_goTypes,
		DependencyIndexes: file_ziggurat_proto_depIdxs,
		MessageInfos:      file_ziggurat_proto_msgTypes,
	}.Build()
	File_ziggurat_proto = out.File
	file_ziggurat_proto_goTypes = nil
	file_ziggurat_proto_depIdxs = nil
}
