// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: ziggurat.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZigguratNode_DispatchTask_FullMethodName  = "/ziggurat.ZigguratNode/DispatchTask"
	ZigguratNode_TaskResult_FullMethodName    = "/ziggurat.ZigguratNode/TaskResult"
	ZigguratNode_PullShard_FullMethodName     = "/ziggurat.ZigguratNode/PullShard"
	ZigguratNode_PushShard_FullMethodName     = "/ziggurat.ZigguratNode/PushShard"
	ZigguratNode_PullECShard_FullMethodName   = "/ziggurat.ZigguratNode/PullECShard"
	ZigguratNode_RetireReplica_FullMethodName = "/ziggurat.ZigguratNode/RetireReplica"
)

// ZigguratNodeClient is the client API for ZigguratNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ZigguratNode is the inter-node RPC service. Every node in the cluster
// exposes this on the gRPC port (default 7101).
type ZigguratNodeClient interface {
	// DispatchTask sends a task to this node for execution. The coordinator
	// calls this on the selected worker after locality/load scoring.
	DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error)
	// TaskResult streams back the result once the task completes. The
	// coordinator calls this to collect output from a remote worker.
	TaskResult(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*TaskResultResponse, error)
	// PullShard downloads an object's data from this node. Used by workers
	// to fetch task inputs that aren't local, and by the replication system
	// to copy objects between nodes.
	PullShard(ctx context.Context, in *PullShardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardData], error)
	// PushShard uploads an object's data to this node. Used by the
	// replication system to write replicas. The first message in the stream
	// MUST carry the header (hash + size); subsequent messages carry data chunks.
	PushShard(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushShardMsg, PushShardResponse], error)
	// PullECShard downloads a single erasure-coded shard from this node.
	// Used by cross-node EC reconstruction when the local node lacks enough
	// shards to decode the original object.
	PullECShard(ctx context.Context, in *PullECShardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardData], error)
	// RetireReplica tells this node to release its hold on a replica.
	// Unpins and decrements the refcount, allowing GC to reclaim it after
	// the grace period. Used when the origin node's GC collects an object.
	RetireReplica(ctx context.Context, in *RetireReplicaRequest, opts ...grpc.CallOption) (*RetireReplicaResponse, error)
}

type zigguratNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewZigguratNodeClient(cc grpc.ClientConnInterface) ZigguratNodeClient {
	return &zigguratNodeClient{cc}
}

func (c *zigguratNodeClient) DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTaskResponse)
	err := c.cc.Invoke(ctx, ZigguratNode_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zigguratNodeClient) TaskResult(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*TaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultResponse)
	err := c.cc.Invoke(ctx, ZigguratNode_TaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zigguratNodeClient) PullShard(ctx context.Context, in *PullShardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZigguratNode_ServiceDesc.Streams[0], ZigguratNode_PullShard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullShardRequest, ShardData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZigguratNode_PullShardClient = grpc.ServerStreamingClient[ShardData]

func (c *zigguratNodeClient) PushShard(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushShardMsg, PushShardResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZigguratNode_ServiceDesc.Streams[1], ZigguratNode_PushShard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushShardMsg, PushShardResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZigguratNode_PushShardClient = grpc.ClientStreamingClient[PushShardMsg, PushShardResponse]

func (c *zigguratNodeClient) PullECShard(ctx context.Context, in *PullECShardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShardData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZigguratNode_ServiceDesc.Streams[2], ZigguratNode_PullECShard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullECShardRequest, ShardData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZigguratNode_PullECShardClient = grpc.ServerStreamingClient[ShardData]

func (c *zigguratNodeClient) RetireReplica(ctx context.Context, in *RetireReplicaRequest, opts ...grpc.CallOption) (*RetireReplicaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetireReplicaResponse)
	err := c.cc.Invoke(ctx, ZigguratNode_RetireReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZigguratNodeServer is the server API for ZigguratNode service.
// All implementations must embed UnimplementedZigguratNodeServer
// for forward compatibility.
//
// ZigguratNode is the inter-node RPC service. Every node in the cluster
// exposes this on the gRPC port (default 7101).
type ZigguratNodeServer interface {
	// DispatchTask sends a task to this node for execution. The coordinator
	// calls this on the selected worker after locality/load scoring.
	DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error)
	// TaskResult streams back the result once the task completes. The
	// coordinator calls this to collect output from a remote worker.
	TaskResult(context.Context, *TaskResultRequest) (*TaskResultResponse, error)
	// PullShard downloads an object's data from this node. Used by workers
	// to fetch task inputs that aren't local, and by the replication system
	// to copy objects between nodes.
	PullShard(*PullShardRequest, grpc.ServerStreamingServer[ShardData]) error
	// PushShard uploads an object's data to this node. Used by the
	// replication system to write replicas. The first message in the stream
	// MUST carry the header (hash + size); subsequent messages carry data chunks.
	PushShard(grpc.ClientStreamingServer[PushShardMsg, PushShardResponse]) error
	// PullECShard downloads a single erasure-coded shard from this node.
	// Used by cross-node EC reconstruction when the local node lacks enough
	// shards to decode the original object.
	PullECShard(*PullECShardRequest, grpc.ServerStreamingServer[ShardData]) error
	// RetireReplica tells this node to release its hold on a replica.
	// Unpins and decrements the refcount, allowing GC to reclaim it after
	// the grace period. Used when the origin node's GC collects an object.
	RetireReplica(context.Context, *RetireReplicaRequest) (*RetireReplicaResponse, error)
	mustEmbedUnimplementedZigguratNodeServer()
}

// UnimplementedZigguratNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZigguratNodeServer struct{}

func (UnimplementedZigguratNodeServer) DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedZigguratNodeServer) TaskResult(context.Context, *TaskResultRequest) (*TaskResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskResult not implemented")
}
func (UnimplementedZigguratNodeServer) PullShard(*PullShardRequest, grpc.ServerStreamingServer[ShardData]) error {
	return status.Error(codes.Unimplemented, "method PullShard not implemented")
}
func (UnimplementedZigguratNodeServer) PushShard(grpc.ClientStreamingServer[PushShardMsg, PushShardResponse]) error {
	return status.Error(codes.Unimplemented, "method PushShard not implemented")
}
func (UnimplementedZigguratNodeServer) PullECShard(*PullECShardRequest, grpc.ServerStreamingServer[ShardData]) error {
	return status.Error(codes.Unimplemented, "method PullECShard not implemented")
}
func (UnimplementedZigguratNodeServer) RetireReplica(context.Context, *RetireReplicaRequest) (*RetireReplicaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetireReplica not implemented")
}
func (UnimplementedZigguratNodeServer) mustEmbedUnimplementedZigguratNodeServer() {}
func (UnimplementedZigguratNodeServer) testEmbeddedByValue()                      {}

// UnsafeZigguratNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZigguratNodeServer will
// result in compilation errors.
type UnsafeZigguratNodeServer interface {
	mustEmbedUnimplementedZigguratNodeServer()
}

func RegisterZigguratNodeServer(s grpc.ServiceRegistrar, srv ZigguratNodeServer) {
	// If the following call panics, it indicates UnimplementedZigguratNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZigguratNode_ServiceDesc, srv)
}

func _ZigguratNode_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZigguratNodeServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZigguratNode_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZigguratNodeServer).DispatchTask(ctx, req.(*DispatchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZigguratNode_TaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZigguratNodeServer).TaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZigguratNode_TaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZigguratNodeServer).TaskResult(ctx, req.(*TaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZigguratNode_PullShard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullShardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZigguratNodeServer).PullShard(m, &grpc.GenericServerStream[PullShardRequest, ShardData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZigguratNode_PullShardServer = grpc.ServerStreamingServer[ShardData]

func _ZigguratNode_PushShard_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZigguratNodeServer).PushShard(&grpc.GenericServerStream[PushShardMsg, PushShardResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZigguratNode_PushShardServer = grpc.ClientStreamingServer[PushShardMsg, PushShardResponse]

func _ZigguratNode_PullECShard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullECShardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZigguratNodeServer).PullECShard(m, &grpc.GenericServerStream[PullECShardRequest, ShardData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZigguratNode_PullECShardServer = grpc.ServerStreamingServer[ShardData]

func _ZigguratNode_RetireReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetireReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZigguratNodeServer).RetireReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZigguratNode_RetireReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZigguratNodeServer).RetireReplica(ctx, req.(*RetireReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZigguratNode_ServiceDesc is the grpc.ServiceDesc for ZigguratNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZigguratNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ziggurat.ZigguratNode",
	HandlerType: (*ZigguratNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchTask",
			Handler:    _ZigguratNode_DispatchTask_Handler,
		},
		{
			MethodName: "TaskResult",
			Handler:    _ZigguratNode_TaskResult_Handler,
		},
		{
			MethodName: "RetireReplica",
			Handler:    _ZigguratNode_RetireReplica_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullShard",
			Handler:       _ZigguratNode_PullShard_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushShard",
			Handler:       _ZigguratNode_PushShard_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullECShard",
			Handler:       _ZigguratNode_PullECShard_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ziggurat.proto",
}
