package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/syzygyhack/ziggurat/internal/config"
)

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Create default config in ~/.ziggurat/",
		Long: `Generates a commented ziggurat.yaml with LAN defaults inside the data
directory (~/.ziggurat/). The node is immediately startable after init.

If a config file already exists at that path, init refuses to overwrite it.`,
		Args: cobra.NoArgs,
		RunE: runInit,
	}
}

// defaultConfigTemplate is the config written by "ziggurat init".
// It uses comments liberally so new users can tune values without
// reading external docs. The %s placeholder is filled with the
// resolved data directory path (no tilde).
const defaultConfigTemplate = `# Ziggurat configuration — generated by "ziggurat init".
# All values shown are defaults. Uncomment and edit as needed.

node:
  # name: ""                    # human-readable node name (default: hostname)
  # role: hybrid                # hybrid | coordinator | worker
  # tags: []                    # worker tags for --require matching
  # data_dir: %s
  # capabilities:               # key-value pairs for --constraint matching
  #   gpu.vram: 24GB

network:
  bind: 0.0.0.0
  http_port: 7100               # REST API
  grpc_port: 7101               # inter-node transport
  gossip_port: 7102             # memberlist gossip
  # advertise: ""               # public IP if behind NAT

# client:
#   addr: 127.0.0.1:7100        # default server for CLI commands

cluster:
  # seeds: []                   # gossip peers to join on startup
  # name: default               # cluster name for mDNS isolation

storage:
  replication_factor: 2
  # capacity: 0                 # max bytes (0 = unlimited)
  gc_grace_period: 1h
  # erasure:                    # Reed-Solomon coding for large objects (> 64 MB)
  #   enabled: true             # enabled by default
  #   data_shards: 4            # k: shards needed to reconstruct
  #   parity_shards: 2          # m: redundancy shards (needs k+m nodes)

compute:
  # concurrency: 0              # max parallel tasks (0 = NumCPU)
  task_timeout: 5m
  max_output_size: 1073741824   # 1 GB
  cancel_grace: 10s
  max_retained_workspaces: 20
  # env_max_age: 168h           # prune persistent envs after 7 days unused
  # env_max_count: 50           # max persistent envs (FIFO eviction)

resilience:
  task_retries: 2
  dead_letter: true
  # max_queue_depth: 0          # max queued tasks (0 = unlimited)

# security:                     # Phase 1 production security
#   tls:
#     enabled: false            # enable mTLS for inter-node gRPC
#     # certs_dir: ""           # override cert directory
#   # join_token: ""            # shared secret for cluster join
#   # api_token: ""             # bearer token for HTTP API (empty = no auth)

metrics:
  enabled: true
`

func runInit(cmd *cobra.Command, args []string) error {
	dataDir := config.DefaultDataDir()
	cfgPath := filepath.Join(dataDir, "ziggurat.yaml")

	// Don't clobber an existing config.
	if _, err := os.Stat(cfgPath); err == nil {
		return fmt.Errorf("config already exists: %s", cfgPath)
	}

	// Ensure the data directory exists.
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return fmt.Errorf("create data dir: %w", err)
	}

	rendered := fmt.Sprintf(defaultConfigTemplate, dataDir)
	if err := os.WriteFile(cfgPath, []byte(rendered), 0o644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("Config written to %s\n", cfgPath)
	fmt.Println("Edit as needed, then run: ziggurat start")
	return nil
}
